//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ChatEntities : DbContext
    {
        public ChatEntities()
            : base("name=ChatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatGroupInfo> ChatGroupInfoes { get; set; }
        public virtual DbSet<ChatRoomInfo> ChatRoomInfoes { get; set; }
        public virtual DbSet<MessageInfoDetail> MessageInfoDetails { get; set; }
        public virtual DbSet<MessageLikeDetail> MessageLikeDetails { get; set; }
    
        public virtual ObjectResult<usp_GetMessageDetails_Result> usp_GetMessageDetails(Nullable<int> id, Nullable<int> toId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var toIdParameter = toId.HasValue ?
                new ObjectParameter("ToId", toId) :
                new ObjectParameter("ToId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMessageDetails_Result>("usp_GetMessageDetails", idParameter, toIdParameter);
        }
    
        public virtual ObjectResult<usp_GetUsersAndGroups_Result> usp_GetUsersAndGroups(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetUsersAndGroups_Result>("usp_GetUsersAndGroups", idParameter);
        }
    }
}
